CREATE DATABASE ConnectPlus;
Go

CREATE TABLE TipoContato(
IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo NVARCHAR (255) NOT NULL
);

CREATE TABLE Contato(
IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome NVARCHAR (255) NOT NULL,
FormaContato NVARCHAR (255) NOT NULL,
Imagem NVARCHAR(255) NOT NULL,
IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
);